version: "3.8"

# futtatas
# docker-compose -f <PROJECT_PATH>/backend-sampler/etc/docker-compose/docker-compose.local.wildfly.yml up --build --force-recreate
#
# belemaszas
# docker exec -it bs-sample-service /bin/bash
#
# uresbe inditas
# docker run --rm -it docker-compose_sample-service /bin/bash
services:
  sample-service:
    container_name: bs-sample-quarkus-service-dev
    build:
      context: ../../
      dockerfile: etc/docker-compose/quarkus-jvm.dockerfile
#    volumes:
#      - './wildfly/sample.properties:/sampler/wildfly.properties'
    ports:
      - '8080:8080'
      - '9990:9990'
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
networks: 
  default: 
    external: 
      name: bs-local-network
